#!/bin/sh

set -e

BT_CONF=/etc/bluetooth/main.conf
echo "Setting Experimental = true in ${BT_CONF}, (was $(grep '^Experimental =' ${BT_CONF}))"
sed -Ei 's/^#?Experimental.*/Experimental = true/' ${BT_CONF}
